INSERT INTO TBL_NO (ID, NOME) VALUES(1, 'A');
INSERT INTO TBL_NO (ID, NOME) VALUES(2, 'B');
INSERT INTO TBL_NO (ID, NOME) VALUES(3, 'C');
INSERT INTO TBL_NO (ID, NOME) VALUES(4, 'D');
INSERT INTO TBL_NO (ID, NOME) VALUES(5, 'E');

INSERT INTO TBL_ORIGEM_DESTINO (ID, ORIGEM, DESTINO, PESO, NODE_ID) VALUES(1, 'A', 'B', 10, 1);
INSERT INTO TBL_ORIGEM_DESTINO (ID, ORIGEM, DESTINO, PESO, NODE_ID) VALUES(2, 'B', 'D', 15, 2);
INSERT INTO TBL_ORIGEM_DESTINO (ID, ORIGEM, DESTINO, PESO, NODE_ID) VALUES(3, 'A', 'C', 20, 1);
INSERT INTO TBL_ORIGEM_DESTINO (ID, ORIGEM, DESTINO, PESO, NODE_ID) VALUES(4, 'C', 'D', 30, 3);
INSERT INTO TBL_ORIGEM_DESTINO (ID, ORIGEM, DESTINO, PESO, NODE_ID) VALUES(5, 'B', 'E', 50, 2);
INSERT INTO TBL_ORIGEM_DESTINO (ID, ORIGEM, DESTINO, PESO, NODE_ID) VALUES(6, 'D', 'E', 30, 4);
